/* automatically generated by JSCoverage - do not edit */
if (typeof _$jscoverage === 'undefined') _$jscoverage = {};
if (! _$jscoverage['isbn.js']) {
  _$jscoverage['isbn.js'] = [];
  _$jscoverage['isbn.js'][1] = 0;
  _$jscoverage['isbn.js'][3] = 0;
  _$jscoverage['isbn.js'][4] = 0;
  _$jscoverage['isbn.js'][6] = 0;
  _$jscoverage['isbn.js'][14] = 0;
  _$jscoverage['isbn.js'][15] = 0;
  _$jscoverage['isbn.js'][16] = 0;
  _$jscoverage['isbn.js'][18] = 0;
  _$jscoverage['isbn.js'][19] = 0;
  _$jscoverage['isbn.js'][22] = 0;
  _$jscoverage['isbn.js'][23] = 0;
  _$jscoverage['isbn.js'][27] = 0;
  _$jscoverage['isbn.js'][28] = 0;
  _$jscoverage['isbn.js'][31] = 0;
  _$jscoverage['isbn.js'][32] = 0;
  _$jscoverage['isbn.js'][37] = 0;
  _$jscoverage['isbn.js'][38] = 0;
  _$jscoverage['isbn.js'][39] = 0;
  _$jscoverage['isbn.js'][40] = 0;
  _$jscoverage['isbn.js'][41] = 0;
  _$jscoverage['isbn.js'][42] = 0;
  _$jscoverage['isbn.js'][43] = 0;
  _$jscoverage['isbn.js'][46] = 0;
  _$jscoverage['isbn.js'][47] = 0;
  _$jscoverage['isbn.js'][49] = 0;
  _$jscoverage['isbn.js'][51] = 0;
  _$jscoverage['isbn.js'][53] = 0;
  _$jscoverage['isbn.js'][64] = 0;
  _$jscoverage['isbn.js'][65] = 0;
  _$jscoverage['isbn.js'][67] = 0;
}
_$jscoverage['isbn.js'][1]++;
"use strict";
_$jscoverage['isbn.js'][3]++;
var config = require("../config.js");
_$jscoverage['isbn.js'][4]++;
var http = require("http");
_$jscoverage['isbn.js'][6]++;
function Isbn() {
}
_$jscoverage['isbn.js'][14]++;
Isbn.prototype.getBookForUser = (function (number, callback) {
  _$jscoverage['isbn.js'][15]++;
  var options = config.isbn;
  _$jscoverage['isbn.js'][16]++;
  options.path = options.path + number;
  _$jscoverage['isbn.js'][18]++;
  http.request(options, (function (response) {
  _$jscoverage['isbn.js'][19]++;
  var str = "";
  _$jscoverage['isbn.js'][22]++;
  response.on("data", (function (chunk) {
  _$jscoverage['isbn.js'][23]++;
  str += chunk;
}));
  _$jscoverage['isbn.js'][27]++;
  response.on("end", (function () {
  _$jscoverage['isbn.js'][28]++;
  normarizeRes(str, callback);
}));
  _$jscoverage['isbn.js'][31]++;
  response.on("error", (function () {
  _$jscoverage['isbn.js'][32]++;
  callback(203, null);
}));
})).end();
});
_$jscoverage['isbn.js'][37]++;
function normarizeRes(str, callback) {
  _$jscoverage['isbn.js'][38]++;
  var res = jsonp2json(str);
  _$jscoverage['isbn.js'][39]++;
  if (res.data && res.data.length > 0) {
    _$jscoverage['isbn.js'][40]++;
    var resBooks = [];
    _$jscoverage['isbn.js'][41]++;
    var books = res.data;
    _$jscoverage['isbn.js'][42]++;
    books.forEach((function (data) {
  _$jscoverage['isbn.js'][43]++;
  config.book.title = data.title;
  _$jscoverage['isbn.js'][46]++;
  var numArray = data.physical_description_text.match(/[0-9]+/g);
  _$jscoverage['isbn.js'][47]++;
  config.book.pages = numArray[numArray.length - 1];
  _$jscoverage['isbn.js'][49]++;
  resBooks.push(config.book);
}));
    _$jscoverage['isbn.js'][51]++;
    callback(null, resBooks);
  }
  else {
    _$jscoverage['isbn.js'][53]++;
    callback(203, null);
  }
}
_$jscoverage['isbn.js'][64]++;
function jsonp2json(jsonp) {
  _$jscoverage['isbn.js'][65]++;
  return JSON.parse(jsonp);
}
_$jscoverage['isbn.js'][67]++;
module.exports = Isbn;
_$jscoverage['isbn.js'].source = ["'use strict';","","var config = require('../config.js');","var http = require('http');","","function Isbn() {","}","","/**"," * Sends HTTP request to weather provider using this.host and this.buildPath"," * Response is processed by this.responseCallback and returned to the provided callback"," * @param  {Function} callback [description]"," */","Isbn.prototype.getBookForUser = function (number, callback) {","    var options = config.isbn;","    options.path = options.path + number;","","    http.request(options, function(response){","        var str = '';","","        //another chunk of data has been recieved, so append it to `str`","        response.on('data', function (chunk) {","            str += chunk;","        });","","        //the whole response has been recieved, so we just print it out here","        response.on('end', function () {","            normarizeRes(str, callback);","        });","","        response.on('error', function() {","            callback(203, null);","        });","    }).end();","};","","function normarizeRes (str, callback) {","    var res = jsonp2json(str);","   if (res.data &amp;&amp; res.data.length &gt; 0) {","       var resBooks = [];","       var books = res.data;","       books.forEach(function (data) {","           config.book.title = data.title;","","           //For getting number of pages","           var numArray = data.physical_description_text.match(/[0-9]+/g);","           config.book.pages = numArray[numArray.length-1] ;","","            resBooks.push(config.book);","        });","        callback(null, resBooks);","    } else {","        callback(203, null);","    }","","","}","","/**"," * Takes a string representing a JSONP response, and returns an object representing the contained JSON"," * @param {string} jsonp"," * @returns {object}"," */","function jsonp2json(jsonp){","    return JSON.parse(jsonp);","}","module.exports = Isbn;"];
